baseURL = 'https://docs.marginalia.nu/'
languageCode = 'en-us'
title = 'Marginalia Search Engine Software Documentation (WORK IN PROGRESS)'
theme = 'hugo-theme-techdoc'
[params]
  subtitle = ''
  menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

[markup.goldmark.renderer]
  unsafe = true

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
        identifier = 'docs'

    [[menu.main]]
        name = "Search Engine Sources"
        url = "https://git.marginalia.nu/"
        weight = 3
        identifier = 'se-git'


    [[menu.main]]
        name = "Documentation Sources"
        url = "https://github.com/MarginaliaSearch/docs.marginalia.nu"
        weight = 2
        identifier = 'doc-git'


    [[menu.main]]
        name = "Marginalia Search Engine"
        url = "https://search.marginalia.nu/"
        weight = 4
        identifier = 'instance'